name: OpenMRS Smoke Tests

on:
  workflow_dispatch: # temporary, for debugging
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: read

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install --immutable

      # - name: Setup local cache server for Turborepo
      #   uses: felixmosh/turborepo-gh-artifacts@v1
      #   with:
      #     repo-token: ${{ secrets.GITHUB_TOKEN }}
      #     server-token: ${{ secrets.TURBO_SERVER_TOKEN }}

      # - name: Run lint, tests and typecheck code
      #   run: yarn run verify

      # - name: Run build
      #   run: yarn turbo run build --color --api="http://127.0.0.1:9080" --token="${{ secrets.TURBO_SERVER_TOKEN }}" --team="${{ github.repository_owner }}"
      
      - name: Start docker compose
        run: docker-compose -f .e2e/docker-compose.yml up -d
      - name: wait for openmrs instance to start
        run: while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' http://localhost/openmrs/login.htm)" != "200" ]]; do sleep 10; done
      - name: Start local app shell
        run: yarn run:shell &
        env:
          OMRS_PROXY_TARGET: "http://localhost"
      - name: Clone tests
        uses: actions/checkout@v3
        with:
          repository: openmrs/openmrs-test-3refapp
          path: openmrs-test-3refapp
      - name: Run playwright tests
        run: cd openmrs-test-3refapp && yarn install && cd packages/playwright && yarn playwright install && yarn playwright test --project=chromium
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: false
          UI_BASE_URL: "http://localhost:8080/openmrs/spa"
          WS_BASE_URL: "http://localhost:8080/openmrs/ws"
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-reports
          path: openmrs-test-3refapp/packages/playwright/test-results/
          retention-days: 30
